version: 2.1
orbs:
  samvera: samvera/circleci-orb@1.0
jobs:
  bundle_lint_test:
    parameters:
      ruby_version:
        type: string
      rails_version:
        type: string
      project:
        type: string
        default: hydra-pcdm
      bundler_version:
        type: string
        default: 2.3.10
    executor:
      name: 'samvera/ruby_fcrepo_solr_redis_postgres'
      ruby_version: << parameters.ruby_version >>
    environment:
      RAILS_VERSION: << parameters.rails_version >>
    steps:
      - samvera/cached_checkout

      - samvera/bundle_for_gem:
          ruby_version: << parameters.ruby_version >>
          bundler_version: << parameters.bundler_version >>
          project: << parameters.project >>

      - samvera/install_solr_core

      - samvera/rubocop

      - samvera/parallel_rspec

workflows:
  ci:
    jobs:
      - bundle_lint_test:
          name: ruby3-2_rails7-0
          ruby_version: 3.2.0
          rails_version: 7.0.4.1
      - bundle_lint_test:
          name: ruby3-2_rails6-1
          ruby_version: 3.2.0
          rails_version: 6.1.7.1
      - bundle_lint_test:
          name: ruby3-2_rails6-0
          ruby_version: 3.2.0
          rails_version: 6.0.6.1
      - bundle_lint_test:
          name: ruby3-1_rails7-0
          ruby_version: 3.1.3
          rails_version: 7.0.4.1
      - bundle_lint_test:
          name: ruby3-1_rails6-1
          ruby_version: 3.1.3
          rails_version: 6.1.7.1
      - bundle_lint_test:
          name: ruby3-1_rails6-0
          ruby_version: 3.1.3
          rails_version: 6.0.6.1
      - bundle_lint_test:
          name: ruby3-0_rails7-0
          ruby_version: 3.0.5
          rails_version: 7.0.4.1
      - bundle_lint_test:
          name: ruby3-0_rails6-1
          ruby_version: 3.0.5
          rails_version: 6.1.7.1
      - bundle_lint_test:
          name: ruby3-0_rails6-0
          ruby_version: 3.0.5
          rails_version: 6.0.6.1
      - bundle_lint_test:
          name: ruby2-7_rails6-1
          ruby_version: 2.7.7
          rails_version: 6.1.7.1
      - bundle_lint_test:
          name: ruby2-7_rails6-0
          ruby_version: 2.7.7
          rails_version: 6.0.6.1
      - bundle_lint_test:
          name: ruby2-7_rails5-2
          ruby_version: 2.7.7
          rails_version: 5.2.8.1
      - bundle_lint_test:
          name: ruby2-7_rails5-1
          ruby_version: 2.7.7
          rails_version: 5.1.7

  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - bundle_lint_test:
          name: ruby3-2_rails7-0
          ruby_version: 3.2.0
          rails_version: 7.0.4.1
      - bundle_lint_test:
          name: ruby3-2_rails6-1
          ruby_version: 3.2.0
          rails_version: 6.1.7.1
      - bundle_lint_test:
          name: ruby3-2_rails6-0
          ruby_version: 3.2.0
          rails_version: 6.0.6.1
      - bundle_lint_test:
          name: ruby3-1_rails7-0
          ruby_version: 3.1.3
          rails_version: 7.0.4.1
      - bundle_lint_test:
          name: ruby3-1_rails6-1
          ruby_version: 3.1.3
          rails_version: 6.1.7.1
      - bundle_lint_test:
          name: ruby3-1_rails6-0
          ruby_version: 3.1.3
          rails_version: 6.0.6.1
      - bundle_lint_test:
          name: ruby3-0_rails7-0
          ruby_version: 3.0.5
          rails_version: 7.0.4.1
      - bundle_lint_test:
          name: ruby3-0_rails6-1
          ruby_version: 3.0.5
          rails_version: 6.1.7.1
      - bundle_lint_test:
          name: ruby3-0_rails6-0
          ruby_version: 3.0.5
          rails_version: 6.0.6.1
      - bundle_lint_test:
          name: ruby2-7_rails6-1
          ruby_version: 2.7.7
          rails_version: 6.1.7.1
      - bundle_lint_test:
          name: ruby2-7_rails6-0
          ruby_version: 2.7.7
          rails_version: 6.0.6.1
      - bundle_lint_test:
          name: ruby2-7_rails5-2
          ruby_version: 2.7.7
          rails_version: 5.2.8.1
      - bundle_lint_test:
          name: ruby2-7_rails5-1
          ruby_version: 2.7.7
          rails_version: 5.1.7
