version: 2.1
orbs:
  samvera: samvera/circleci-orb@1.0
jobs:
  bundle_lint_test:
    parameters:
      ruby_version:
        type: string
      rails_version:
        type: string
      project:
        type: string
        default: hydra-pcdm
      bundler_version:
        type: string
        default: 2.3.10
    executor:
      name: 'samvera/ruby_fcrepo_solr'
      ruby_version: << parameters.ruby_version >>
    environment:
      RAILS_VERSION: << parameters.rails_version >>
    steps:
      - samvera/cached_checkout

      - samvera/bundle_for_gem:
          ruby_version: << parameters.ruby_version >>
          bundler_version: << parameters.bundler_version >>
          project: << parameters.project >>

      - samvera/install_solr_active_fedora_core

      - samvera/rubocop

      - samvera/parallel_rspec

      - deploy:
          command: curl -k https://coveralls.io/webhook?repo_token=${COVERALLS_REPO_TOKEN} -d "payload[build_num]=${CIRCLE_BUILD_NUM}&payload[status]=done"

workflows:
  ci:
    jobs:
      - bundle_lint_test:
          name: ruby2-7_rails6-0
          ruby_version: 2.7.5
          rails_version: 6.0.2
      - bundle_lint_test:
          name: ruby2-7_rails5-2
          ruby_version: 2.7.5
          rails_version: 5.2.4
      - bundle_lint_test:
          name: ruby2-7_rails5-1
          ruby_version: 2.7.5
          rails_version: 5.1.7
      - bundle_lint_test:
          name: ruby2-6_rails6-0
          ruby_version: 2.6.9
          rails_version: 6.0.2
      - bundle_lint_test:
          name: ruby2-6_rails5-2
          ruby_version: 2.6.9
          rails_version: 5.2.4
      - bundle_lint_test:
          name: ruby2-6_rails5-1
          ruby_version: 2.6.9
          rails_version: 5.1.7
      - bundle_lint_test:
          name: ruby2-5_rails6-0
          ruby_version: 2.5.9
          rails_version: 6.0.2
      - bundle_lint_test:
          name: ruby2-5_rails5-2
          ruby_version: 2.5.9
          rails_version: 5.2.4
      - bundle_lint_test:
          name: ruby2-5_rails5-1
          ruby_version: 2.5.9
          rails_version: 5.2.4

  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - bundle_lint_test:
          name: ruby2-7_rails6-0
          ruby_version: 2.7.5
          rails_version: 6.0.2
      - bundle_lint_test:
          name: ruby2-7_rails5-2
          ruby_version: 2.7.5
          rails_version: 5.2.4
      - bundle_lint_test:
          name: ruby2-7_rails5-1
          ruby_version: 2.7.5
          rails_version: 5.1.7
      - bundle_lint_test:
          name: ruby2-6_rails6-0
          ruby_version: 2.6.9
          rails_version: 6.0.2
      - bundle_lint_test:
          name: ruby2-6_rails5-2
          ruby_version: 2.6.9
          rails_version: 5.2.4
      - bundle_lint_test:
          name: ruby2-6_rails5-1
          ruby_version: 2.6.9
          rails_version: 5.1.7
      - bundle_lint_test:
          name: ruby2-5_rails6-0
          ruby_version: 2.5.9
          rails_version: 6.0.2
      - bundle_lint_test:
          name: ruby2-5_rails5-2
          ruby_version: 2.5.9
          rails_version: 5.2.4
      - bundle_lint_test:
          name: ruby2-5_rails5-1
          ruby_version: 2.5.9
          rails_version: 5.2.4
